# API Keys - Replace with your actual keys
api_keys:
  noaa: "CiulaYXmbEBqtdKkwTBkgUNWkMrTFHKa"
  eia: "Er1DH6AWQuWRNOBY6ijBIlGuOXWk7XR3din5lCFZ"

api_urls:
  # noaa: "https://www.ncdc.noaa.gov/cdo-web/datasets"
  noaa: "https://www.ncei.noaa.gov/cdo-web/api/v2"
  # eia: "https://www.eia.gov/electricity/data/browser/"
  eia: "https://api.eia.gov/v2/electricity/"

# List of cities and their corresponding EIA region
cities:
  - name: "New York"
    state: "NY"
    noaa_station_id: "GHCND:USW00094728"
    eia_region_code: "NYIS"
    # eia_series_code: "ELEC.SALES.NY-RES.M"
    latitude: 40.7811
    longitude: -73.9667

  - name: "Chicago"
    state: "IL"
    noaa_station_id: "GHCND:USW00094846"
    eia_region_code: "MISO"
    # eia_series_id: "ELEC.SALES.IL-RES.M"
    latitude: 41.9742
    longitude: -87.9073

  - name: "Houston"
    state: "TX"
    noaa_station_id: "GHCND:USW00012918"
    eia_region_code: "TX"
    # eia_series_id: "ELEC.SALES.TX-RES.M"
    latitude: 29.9902
    longitude: -95.3368

  - name: "Phoenix"
    state: "AZ"
    noaa_station_id: "GHCND:USW00023183"
    eia_region_code: "AZPS"
    # eia_series_id: "ELEC.SALES.AZ-RES.M"
    latitude: 33.4373
    longitude: -112.0079

  - name: "Seattle"
    state: "WA"
    noaa_station_id: "GHCND:USW00024233"
    eia_region_code: "BPAT"
    # eia_series_id: "ELEC.SALES.WA-RES.M"
    latitude: 47.4435
    longitude: -122.3012


# Data Quality Parameters
data_quality:
  max_days_old: 3
  outlier_thresholds:
    temp_celsius:
      max: 55
      min: -45
    energy_mwh:
      min: 0